// <auto-generated />
namespace PokeSim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Attack_AttackMethodId_Namechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Attack_AttackMethodId_Namechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201703111123151_Attack_AttackMethodId_Namechange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
